env:
  browser: true
  es2020: true
  node: true
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  no-tabs: 0
  no-empty-function: 
    - error 
    - allow: 
      - constructors
  indent:
  - error
  - tab
  react/jsx-indent:
    - 1
    - tab
  semi:
    - error
    - never
  object-curly-spacing:
    - error
    - never
  no-console:
    - off
  react/jsx-indent-props:
  - 2
  - tab
  react/jsx-one-expression-per-line: 0
  object-curly-newline:
  - error
  - multiline: true
    minProperties: 3

